'''
PUT YOUR MAPBOX API KEY HERE 
IT SHOULD LOOK LIKE 
MAPBOX_KEY = "YOUR KEY HERE IN QUOTES"
'''
MAPBOX_KEY = "pk.eyJ1IjoianVuZWJ1Z2d5IiwiYSI6ImNrY2YyMnE1eDBidmkyemsyOWZjbzU0Z24ifQ.mCT9XQLM_LyYO25qTN7xUQ"

