"""
Test file for simplifying a gpx file using gpx.simplify 
"""
import os
import utm
import requests
import sys
import gpxpy
import gpxpy.gpx
import gpxpy.geo as mod_geo
import json
import xml.etree.ElementTree as ET


 # pk.eyJ1IjoianVuZWJ1Z2d5IiwiYSI6ImNrY2YyMnE1eDBidmkyemsyOWZjbzU0Z24ifQ.mCT9XQLM_LyYO25qTN7xUQ 
def callMapBox():
    """
    Takes a gpx file, opens it, simplifies, gets coords, calls mapbox, 
    outputs route generated by mapbox 


    Considerations: 
        user gives gpx
        server reads and simplifies gpx based on number of points
        one mapbox call == 25 points

        do untill processed all points
            in increments of 25 points 
                call mapbox api with coordinates
                reciveve mabox coordinates and que sheet
                compare differences between user and mapbox coordinates
                if n coordinates differ by x amount 
                    run api again on an unsimplified version of that segment
                    do untill no diff for that segment
                
                if no major differences between user gpx and mapbox coords,
                    add instructions to que sheet
        
        present que sheet to user 

    """
   
for elem in tree.findall("{http://www.topografix.com/GPX/1/1}wpt"):
    print elem.attrib['lon'], elem.attrib['lat']

    pp = pprint.PrettyPrinter(indent=4)

    gpx_file = open(sys.argv[1], 'r')
    mygpx = gpxpy.parse(gpx_file)
    
    mygpx.simplify(300)
    data_dict = xmltodict.parse(mygpx.to_xml()) 

     tree = ET.parse(mygpx.to_xml())

    result = json.dumps(data_dict)
    pp.pprint(result)




    # payload = {"coordinates" : """Coords go here"""}

    # r = requests.get("https://api.mapbox.com/directions/v5/cycling/", params=payload)
    # print(r.text)
  
    #  https://api.mapbox.com/directions/v5/cycling/{coordinates} 


def main():

    # TODO need to change it so that we get the file from the website
    gpx_file = open(sys.argv[1], 'r')
    mygpx = gpxpy.parse(gpx_file)

    for track in mygpx.tracks:
        for segment in track.segments:
            i = 0
            for point in segment.points:
                i+=1
        print(f"There were {i} many points in the gpx file")

    mygpx.simplify(300)



    for track in mygpx.tracks:
        for segment in track.segments:
            i = 0
            for point in segment.points:
                i+=1
        print(f"There were {i} many points in the gpx file after simplification")

    output = open("out.gpx", "w")
    output.write(mygpx.to_xml())
    output.close()



if __name__ == "__main__":
    callMapBox()